// Code generated by mockery v2.45.0. DO NOT EDIT.

package mocks

import (
	avahi "github.com/enbility/go-avahi"
	dbus "github.com/godbus/dbus/v5"

	mock "github.com/stretchr/testify/mock"
)

// AddressResolverInterface is an autogenerated mock type for the AddressResolverInterface type
type AddressResolverInterface struct {
	mock.Mock
}

type AddressResolverInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *AddressResolverInterface) EXPECT() *AddressResolverInterface_Expecter {
	return &AddressResolverInterface_Expecter{mock: &_m.Mock}
}

// DispatchSignal provides a mock function with given fields: signal
func (_m *AddressResolverInterface) DispatchSignal(signal *dbus.Signal) error {
	ret := _m.Called(signal)

	if len(ret) == 0 {
		panic("no return value specified for DispatchSignal")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*dbus.Signal) error); ok {
		r0 = rf(signal)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// AddressResolverInterface_DispatchSignal_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DispatchSignal'
type AddressResolverInterface_DispatchSignal_Call struct {
	*mock.Call
}

// DispatchSignal is a helper method to define mock.On call
//   - signal *dbus.Signal
func (_e *AddressResolverInterface_Expecter) DispatchSignal(signal interface{}) *AddressResolverInterface_DispatchSignal_Call {
	return &AddressResolverInterface_DispatchSignal_Call{Call: _e.mock.On("DispatchSignal", signal)}
}

func (_c *AddressResolverInterface_DispatchSignal_Call) Run(run func(signal *dbus.Signal)) *AddressResolverInterface_DispatchSignal_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*dbus.Signal))
	})
	return _c
}

func (_c *AddressResolverInterface_DispatchSignal_Call) Return(_a0 error) *AddressResolverInterface_DispatchSignal_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *AddressResolverInterface_DispatchSignal_Call) RunAndReturn(run func(*dbus.Signal) error) *AddressResolverInterface_DispatchSignal_Call {
	_c.Call.Return(run)
	return _c
}

// FoundChannel provides a mock function with given fields:
func (_m *AddressResolverInterface) FoundChannel() chan avahi.Address {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for FoundChannel")
	}

	var r0 chan avahi.Address
	if rf, ok := ret.Get(0).(func() chan avahi.Address); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(chan avahi.Address)
		}
	}

	return r0
}

// AddressResolverInterface_FoundChannel_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FoundChannel'
type AddressResolverInterface_FoundChannel_Call struct {
	*mock.Call
}

// FoundChannel is a helper method to define mock.On call
func (_e *AddressResolverInterface_Expecter) FoundChannel() *AddressResolverInterface_FoundChannel_Call {
	return &AddressResolverInterface_FoundChannel_Call{Call: _e.mock.On("FoundChannel")}
}

func (_c *AddressResolverInterface_FoundChannel_Call) Run(run func()) *AddressResolverInterface_FoundChannel_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *AddressResolverInterface_FoundChannel_Call) Return(_a0 chan avahi.Address) *AddressResolverInterface_FoundChannel_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *AddressResolverInterface_FoundChannel_Call) RunAndReturn(run func() chan avahi.Address) *AddressResolverInterface_FoundChannel_Call {
	_c.Call.Return(run)
	return _c
}

// Free provides a mock function with given fields:
func (_m *AddressResolverInterface) Free() {
	_m.Called()
}

// AddressResolverInterface_Free_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Free'
type AddressResolverInterface_Free_Call struct {
	*mock.Call
}

// Free is a helper method to define mock.On call
func (_e *AddressResolverInterface_Expecter) Free() *AddressResolverInterface_Free_Call {
	return &AddressResolverInterface_Free_Call{Call: _e.mock.On("Free")}
}

func (_c *AddressResolverInterface_Free_Call) Run(run func()) *AddressResolverInterface_Free_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *AddressResolverInterface_Free_Call) Return() *AddressResolverInterface_Free_Call {
	_c.Call.Return()
	return _c
}

func (_c *AddressResolverInterface_Free_Call) RunAndReturn(run func()) *AddressResolverInterface_Free_Call {
	_c.Call.Return(run)
	return _c
}

// GetObjectPath provides a mock function with given fields:
func (_m *AddressResolverInterface) GetObjectPath() dbus.ObjectPath {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetObjectPath")
	}

	var r0 dbus.ObjectPath
	if rf, ok := ret.Get(0).(func() dbus.ObjectPath); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(dbus.ObjectPath)
	}

	return r0
}

// AddressResolverInterface_GetObjectPath_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetObjectPath'
type AddressResolverInterface_GetObjectPath_Call struct {
	*mock.Call
}

// GetObjectPath is a helper method to define mock.On call
func (_e *AddressResolverInterface_Expecter) GetObjectPath() *AddressResolverInterface_GetObjectPath_Call {
	return &AddressResolverInterface_GetObjectPath_Call{Call: _e.mock.On("GetObjectPath")}
}

func (_c *AddressResolverInterface_GetObjectPath_Call) Run(run func()) *AddressResolverInterface_GetObjectPath_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *AddressResolverInterface_GetObjectPath_Call) Return(_a0 dbus.ObjectPath) *AddressResolverInterface_GetObjectPath_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *AddressResolverInterface_GetObjectPath_Call) RunAndReturn(run func() dbus.ObjectPath) *AddressResolverInterface_GetObjectPath_Call {
	_c.Call.Return(run)
	return _c
}

// NewAddressResolverInterface creates a new instance of AddressResolverInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAddressResolverInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *AddressResolverInterface {
	mock := &AddressResolverInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
