// Code generated by mockery v2.45.0. DO NOT EDIT.

package mocks

import (
	avahi "github.com/enbility/go-avahi"
	dbus "github.com/godbus/dbus/v5"

	mock "github.com/stretchr/testify/mock"
)

// HostNameResolverInterface is an autogenerated mock type for the HostNameResolverInterface type
type HostNameResolverInterface struct {
	mock.Mock
}

type HostNameResolverInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *HostNameResolverInterface) EXPECT() *HostNameResolverInterface_Expecter {
	return &HostNameResolverInterface_Expecter{mock: &_m.Mock}
}

// DispatchSignal provides a mock function with given fields: signal
func (_m *HostNameResolverInterface) DispatchSignal(signal *dbus.Signal) error {
	ret := _m.Called(signal)

	if len(ret) == 0 {
		panic("no return value specified for DispatchSignal")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*dbus.Signal) error); ok {
		r0 = rf(signal)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// HostNameResolverInterface_DispatchSignal_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DispatchSignal'
type HostNameResolverInterface_DispatchSignal_Call struct {
	*mock.Call
}

// DispatchSignal is a helper method to define mock.On call
//   - signal *dbus.Signal
func (_e *HostNameResolverInterface_Expecter) DispatchSignal(signal interface{}) *HostNameResolverInterface_DispatchSignal_Call {
	return &HostNameResolverInterface_DispatchSignal_Call{Call: _e.mock.On("DispatchSignal", signal)}
}

func (_c *HostNameResolverInterface_DispatchSignal_Call) Run(run func(signal *dbus.Signal)) *HostNameResolverInterface_DispatchSignal_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*dbus.Signal))
	})
	return _c
}

func (_c *HostNameResolverInterface_DispatchSignal_Call) Return(_a0 error) *HostNameResolverInterface_DispatchSignal_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *HostNameResolverInterface_DispatchSignal_Call) RunAndReturn(run func(*dbus.Signal) error) *HostNameResolverInterface_DispatchSignal_Call {
	_c.Call.Return(run)
	return _c
}

// FoundChannel provides a mock function with given fields:
func (_m *HostNameResolverInterface) FoundChannel() chan avahi.HostName {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for FoundChannel")
	}

	var r0 chan avahi.HostName
	if rf, ok := ret.Get(0).(func() chan avahi.HostName); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(chan avahi.HostName)
		}
	}

	return r0
}

// HostNameResolverInterface_FoundChannel_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FoundChannel'
type HostNameResolverInterface_FoundChannel_Call struct {
	*mock.Call
}

// FoundChannel is a helper method to define mock.On call
func (_e *HostNameResolverInterface_Expecter) FoundChannel() *HostNameResolverInterface_FoundChannel_Call {
	return &HostNameResolverInterface_FoundChannel_Call{Call: _e.mock.On("FoundChannel")}
}

func (_c *HostNameResolverInterface_FoundChannel_Call) Run(run func()) *HostNameResolverInterface_FoundChannel_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *HostNameResolverInterface_FoundChannel_Call) Return(_a0 chan avahi.HostName) *HostNameResolverInterface_FoundChannel_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *HostNameResolverInterface_FoundChannel_Call) RunAndReturn(run func() chan avahi.HostName) *HostNameResolverInterface_FoundChannel_Call {
	_c.Call.Return(run)
	return _c
}

// Free provides a mock function with given fields:
func (_m *HostNameResolverInterface) Free() {
	_m.Called()
}

// HostNameResolverInterface_Free_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Free'
type HostNameResolverInterface_Free_Call struct {
	*mock.Call
}

// Free is a helper method to define mock.On call
func (_e *HostNameResolverInterface_Expecter) Free() *HostNameResolverInterface_Free_Call {
	return &HostNameResolverInterface_Free_Call{Call: _e.mock.On("Free")}
}

func (_c *HostNameResolverInterface_Free_Call) Run(run func()) *HostNameResolverInterface_Free_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *HostNameResolverInterface_Free_Call) Return() *HostNameResolverInterface_Free_Call {
	_c.Call.Return()
	return _c
}

func (_c *HostNameResolverInterface_Free_Call) RunAndReturn(run func()) *HostNameResolverInterface_Free_Call {
	_c.Call.Return(run)
	return _c
}

// GetObjectPath provides a mock function with given fields:
func (_m *HostNameResolverInterface) GetObjectPath() dbus.ObjectPath {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetObjectPath")
	}

	var r0 dbus.ObjectPath
	if rf, ok := ret.Get(0).(func() dbus.ObjectPath); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(dbus.ObjectPath)
	}

	return r0
}

// HostNameResolverInterface_GetObjectPath_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetObjectPath'
type HostNameResolverInterface_GetObjectPath_Call struct {
	*mock.Call
}

// GetObjectPath is a helper method to define mock.On call
func (_e *HostNameResolverInterface_Expecter) GetObjectPath() *HostNameResolverInterface_GetObjectPath_Call {
	return &HostNameResolverInterface_GetObjectPath_Call{Call: _e.mock.On("GetObjectPath")}
}

func (_c *HostNameResolverInterface_GetObjectPath_Call) Run(run func()) *HostNameResolverInterface_GetObjectPath_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *HostNameResolverInterface_GetObjectPath_Call) Return(_a0 dbus.ObjectPath) *HostNameResolverInterface_GetObjectPath_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *HostNameResolverInterface_GetObjectPath_Call) RunAndReturn(run func() dbus.ObjectPath) *HostNameResolverInterface_GetObjectPath_Call {
	_c.Call.Return(run)
	return _c
}

// NewHostNameResolverInterface creates a new instance of HostNameResolverInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewHostNameResolverInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *HostNameResolverInterface {
	mock := &HostNameResolverInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
