// Code generated by mockery v2.45.0. DO NOT EDIT.

package mocks

import (
	avahi "github.com/enbility/go-avahi"
	dbus "github.com/godbus/dbus/v5"

	mock "github.com/stretchr/testify/mock"
)

// RecordBrowserInterface is an autogenerated mock type for the RecordBrowserInterface type
type RecordBrowserInterface struct {
	mock.Mock
}

type RecordBrowserInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *RecordBrowserInterface) EXPECT() *RecordBrowserInterface_Expecter {
	return &RecordBrowserInterface_Expecter{mock: &_m.Mock}
}

// AddChannel provides a mock function with given fields:
func (_m *RecordBrowserInterface) AddChannel() chan avahi.Record {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for AddChannel")
	}

	var r0 chan avahi.Record
	if rf, ok := ret.Get(0).(func() chan avahi.Record); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(chan avahi.Record)
		}
	}

	return r0
}

// RecordBrowserInterface_AddChannel_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddChannel'
type RecordBrowserInterface_AddChannel_Call struct {
	*mock.Call
}

// AddChannel is a helper method to define mock.On call
func (_e *RecordBrowserInterface_Expecter) AddChannel() *RecordBrowserInterface_AddChannel_Call {
	return &RecordBrowserInterface_AddChannel_Call{Call: _e.mock.On("AddChannel")}
}

func (_c *RecordBrowserInterface_AddChannel_Call) Run(run func()) *RecordBrowserInterface_AddChannel_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *RecordBrowserInterface_AddChannel_Call) Return(_a0 chan avahi.Record) *RecordBrowserInterface_AddChannel_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *RecordBrowserInterface_AddChannel_Call) RunAndReturn(run func() chan avahi.Record) *RecordBrowserInterface_AddChannel_Call {
	_c.Call.Return(run)
	return _c
}

// DispatchSignal provides a mock function with given fields: signal
func (_m *RecordBrowserInterface) DispatchSignal(signal *dbus.Signal) error {
	ret := _m.Called(signal)

	if len(ret) == 0 {
		panic("no return value specified for DispatchSignal")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*dbus.Signal) error); ok {
		r0 = rf(signal)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// RecordBrowserInterface_DispatchSignal_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DispatchSignal'
type RecordBrowserInterface_DispatchSignal_Call struct {
	*mock.Call
}

// DispatchSignal is a helper method to define mock.On call
//   - signal *dbus.Signal
func (_e *RecordBrowserInterface_Expecter) DispatchSignal(signal interface{}) *RecordBrowserInterface_DispatchSignal_Call {
	return &RecordBrowserInterface_DispatchSignal_Call{Call: _e.mock.On("DispatchSignal", signal)}
}

func (_c *RecordBrowserInterface_DispatchSignal_Call) Run(run func(signal *dbus.Signal)) *RecordBrowserInterface_DispatchSignal_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*dbus.Signal))
	})
	return _c
}

func (_c *RecordBrowserInterface_DispatchSignal_Call) Return(_a0 error) *RecordBrowserInterface_DispatchSignal_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *RecordBrowserInterface_DispatchSignal_Call) RunAndReturn(run func(*dbus.Signal) error) *RecordBrowserInterface_DispatchSignal_Call {
	_c.Call.Return(run)
	return _c
}

// Free provides a mock function with given fields:
func (_m *RecordBrowserInterface) Free() {
	_m.Called()
}

// RecordBrowserInterface_Free_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Free'
type RecordBrowserInterface_Free_Call struct {
	*mock.Call
}

// Free is a helper method to define mock.On call
func (_e *RecordBrowserInterface_Expecter) Free() *RecordBrowserInterface_Free_Call {
	return &RecordBrowserInterface_Free_Call{Call: _e.mock.On("Free")}
}

func (_c *RecordBrowserInterface_Free_Call) Run(run func()) *RecordBrowserInterface_Free_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *RecordBrowserInterface_Free_Call) Return() *RecordBrowserInterface_Free_Call {
	_c.Call.Return()
	return _c
}

func (_c *RecordBrowserInterface_Free_Call) RunAndReturn(run func()) *RecordBrowserInterface_Free_Call {
	_c.Call.Return(run)
	return _c
}

// GetObjectPath provides a mock function with given fields:
func (_m *RecordBrowserInterface) GetObjectPath() dbus.ObjectPath {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetObjectPath")
	}

	var r0 dbus.ObjectPath
	if rf, ok := ret.Get(0).(func() dbus.ObjectPath); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(dbus.ObjectPath)
	}

	return r0
}

// RecordBrowserInterface_GetObjectPath_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetObjectPath'
type RecordBrowserInterface_GetObjectPath_Call struct {
	*mock.Call
}

// GetObjectPath is a helper method to define mock.On call
func (_e *RecordBrowserInterface_Expecter) GetObjectPath() *RecordBrowserInterface_GetObjectPath_Call {
	return &RecordBrowserInterface_GetObjectPath_Call{Call: _e.mock.On("GetObjectPath")}
}

func (_c *RecordBrowserInterface_GetObjectPath_Call) Run(run func()) *RecordBrowserInterface_GetObjectPath_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *RecordBrowserInterface_GetObjectPath_Call) Return(_a0 dbus.ObjectPath) *RecordBrowserInterface_GetObjectPath_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *RecordBrowserInterface_GetObjectPath_Call) RunAndReturn(run func() dbus.ObjectPath) *RecordBrowserInterface_GetObjectPath_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveChannel provides a mock function with given fields:
func (_m *RecordBrowserInterface) RemoveChannel() chan avahi.Record {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for RemoveChannel")
	}

	var r0 chan avahi.Record
	if rf, ok := ret.Get(0).(func() chan avahi.Record); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(chan avahi.Record)
		}
	}

	return r0
}

// RecordBrowserInterface_RemoveChannel_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveChannel'
type RecordBrowserInterface_RemoveChannel_Call struct {
	*mock.Call
}

// RemoveChannel is a helper method to define mock.On call
func (_e *RecordBrowserInterface_Expecter) RemoveChannel() *RecordBrowserInterface_RemoveChannel_Call {
	return &RecordBrowserInterface_RemoveChannel_Call{Call: _e.mock.On("RemoveChannel")}
}

func (_c *RecordBrowserInterface_RemoveChannel_Call) Run(run func()) *RecordBrowserInterface_RemoveChannel_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *RecordBrowserInterface_RemoveChannel_Call) Return(_a0 chan avahi.Record) *RecordBrowserInterface_RemoveChannel_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *RecordBrowserInterface_RemoveChannel_Call) RunAndReturn(run func() chan avahi.Record) *RecordBrowserInterface_RemoveChannel_Call {
	_c.Call.Return(run)
	return _c
}

// NewRecordBrowserInterface creates a new instance of RecordBrowserInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRecordBrowserInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *RecordBrowserInterface {
	mock := &RecordBrowserInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
