// Code generated by mockery v2.45.0. DO NOT EDIT.

package mocks

import (
	avahi "github.com/enbility/go-avahi"
	dbus "github.com/godbus/dbus/v5"

	mock "github.com/stretchr/testify/mock"
)

// ServiceResolverInterface is an autogenerated mock type for the ServiceResolverInterface type
type ServiceResolverInterface struct {
	mock.Mock
}

type ServiceResolverInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *ServiceResolverInterface) EXPECT() *ServiceResolverInterface_Expecter {
	return &ServiceResolverInterface_Expecter{mock: &_m.Mock}
}

// DispatchSignal provides a mock function with given fields: signal
func (_m *ServiceResolverInterface) DispatchSignal(signal *dbus.Signal) error {
	ret := _m.Called(signal)

	if len(ret) == 0 {
		panic("no return value specified for DispatchSignal")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*dbus.Signal) error); ok {
		r0 = rf(signal)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ServiceResolverInterface_DispatchSignal_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DispatchSignal'
type ServiceResolverInterface_DispatchSignal_Call struct {
	*mock.Call
}

// DispatchSignal is a helper method to define mock.On call
//   - signal *dbus.Signal
func (_e *ServiceResolverInterface_Expecter) DispatchSignal(signal interface{}) *ServiceResolverInterface_DispatchSignal_Call {
	return &ServiceResolverInterface_DispatchSignal_Call{Call: _e.mock.On("DispatchSignal", signal)}
}

func (_c *ServiceResolverInterface_DispatchSignal_Call) Run(run func(signal *dbus.Signal)) *ServiceResolverInterface_DispatchSignal_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*dbus.Signal))
	})
	return _c
}

func (_c *ServiceResolverInterface_DispatchSignal_Call) Return(_a0 error) *ServiceResolverInterface_DispatchSignal_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ServiceResolverInterface_DispatchSignal_Call) RunAndReturn(run func(*dbus.Signal) error) *ServiceResolverInterface_DispatchSignal_Call {
	_c.Call.Return(run)
	return _c
}

// FoundChannel provides a mock function with given fields:
func (_m *ServiceResolverInterface) FoundChannel() chan avahi.Service {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for FoundChannel")
	}

	var r0 chan avahi.Service
	if rf, ok := ret.Get(0).(func() chan avahi.Service); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(chan avahi.Service)
		}
	}

	return r0
}

// ServiceResolverInterface_FoundChannel_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FoundChannel'
type ServiceResolverInterface_FoundChannel_Call struct {
	*mock.Call
}

// FoundChannel is a helper method to define mock.On call
func (_e *ServiceResolverInterface_Expecter) FoundChannel() *ServiceResolverInterface_FoundChannel_Call {
	return &ServiceResolverInterface_FoundChannel_Call{Call: _e.mock.On("FoundChannel")}
}

func (_c *ServiceResolverInterface_FoundChannel_Call) Run(run func()) *ServiceResolverInterface_FoundChannel_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *ServiceResolverInterface_FoundChannel_Call) Return(_a0 chan avahi.Service) *ServiceResolverInterface_FoundChannel_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ServiceResolverInterface_FoundChannel_Call) RunAndReturn(run func() chan avahi.Service) *ServiceResolverInterface_FoundChannel_Call {
	_c.Call.Return(run)
	return _c
}

// Free provides a mock function with given fields:
func (_m *ServiceResolverInterface) Free() {
	_m.Called()
}

// ServiceResolverInterface_Free_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Free'
type ServiceResolverInterface_Free_Call struct {
	*mock.Call
}

// Free is a helper method to define mock.On call
func (_e *ServiceResolverInterface_Expecter) Free() *ServiceResolverInterface_Free_Call {
	return &ServiceResolverInterface_Free_Call{Call: _e.mock.On("Free")}
}

func (_c *ServiceResolverInterface_Free_Call) Run(run func()) *ServiceResolverInterface_Free_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *ServiceResolverInterface_Free_Call) Return() *ServiceResolverInterface_Free_Call {
	_c.Call.Return()
	return _c
}

func (_c *ServiceResolverInterface_Free_Call) RunAndReturn(run func()) *ServiceResolverInterface_Free_Call {
	_c.Call.Return(run)
	return _c
}

// GetObjectPath provides a mock function with given fields:
func (_m *ServiceResolverInterface) GetObjectPath() dbus.ObjectPath {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetObjectPath")
	}

	var r0 dbus.ObjectPath
	if rf, ok := ret.Get(0).(func() dbus.ObjectPath); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(dbus.ObjectPath)
	}

	return r0
}

// ServiceResolverInterface_GetObjectPath_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetObjectPath'
type ServiceResolverInterface_GetObjectPath_Call struct {
	*mock.Call
}

// GetObjectPath is a helper method to define mock.On call
func (_e *ServiceResolverInterface_Expecter) GetObjectPath() *ServiceResolverInterface_GetObjectPath_Call {
	return &ServiceResolverInterface_GetObjectPath_Call{Call: _e.mock.On("GetObjectPath")}
}

func (_c *ServiceResolverInterface_GetObjectPath_Call) Run(run func()) *ServiceResolverInterface_GetObjectPath_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *ServiceResolverInterface_GetObjectPath_Call) Return(_a0 dbus.ObjectPath) *ServiceResolverInterface_GetObjectPath_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ServiceResolverInterface_GetObjectPath_Call) RunAndReturn(run func() dbus.ObjectPath) *ServiceResolverInterface_GetObjectPath_Call {
	_c.Call.Return(run)
	return _c
}

// NewServiceResolverInterface creates a new instance of ServiceResolverInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewServiceResolverInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *ServiceResolverInterface {
	mock := &ServiceResolverInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
